### ISSUE TITLE
No documentation available :-(

### ISSUE THREAD

**Issue by txnfail** [andremartingo/java-mindera-graduate-2018#1]
Please add some documentation on how to run the project locally. Although I was unable to run the code locally, from my review I suspect it will not work correctly when processing large 20000x20000 matrixes.

**Comment by andremartingo** [comment]
Thanks for the feedback. I will add the documentation soon as possible 👍

**Comment by andremartingo** [comment]
- Already added the documentation to run the application with .json file.
- Refactor all algorithm to support large matrix, although i couldn't test because my laptop doesn't have enough memory. @jaafonseca
